config/routes.rb
Rails.application.routes.draw do



  constraints Clearance::Constraints::SignedIn.new { |user| user.admin? } do
    resources :companies

    resources :campuses do
      resources :rooms do
        resources :events
      end
    end
  end

  get 'company' => 'companies#show'

  constraints Clearance::Constraints::SignedIn.new do

    delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
    resources :users
    resources :invites
    resources :comments
    resources :amenities

    resources :campuses do
      resources :rooms, only: [:show, :index] do
        resources :events
      end
    end

    get 'campuses/:campus_id/events' => 'campuses#events'

    post 'invite_codes' => "invite_codes#create"
    root 'dashboard#home'

    resources :passwords, controller: "clearance/passwords", only: [:create, :new]
    resource :session, controller: "clearance/sessions", only: [:create]

    resources :users, controller: "clearance/users", only: [:create] do
      resource :password,
        controller: "clearance/passwords",
        only: [:create, :edit, :update]
    end
  end

  constraints Clearance::Constraints::SignedOut.new do
    resources :passwords, controller: "clearance/passwords", only: [:create, :new]
    resource :session, controller: "clearance/sessions", only: [:create]

    resources :users, only: [:new, :create]

    resources :users, controller: "clearance/users", except: [:create] do
      resource :password,
        controller: "clearance/passwords",
        only: [:create, :edit, :update]
    end

    get "/sign_in" => "clearance/sessions#new", as: "sign_in"
    get "/sign_up" => "clearance/users#new", as: "sign_up"

    root "clearance/sessions#new", as: :guest_root
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  before_action :require_login


  def home
    @user = current_user
    @user_pending_invites = @user.invites.where(status: Invite::PENDING).includes(:event, :room)
    @user_accepted_invites = @user.invites.where(status: Invite::ACCEPTED).includes(:event, :room)
    @user_accepted_invites += @user.invites.where(status: Invite::REMOTE).includes(:event, :room)
    @events = @user.upcoming_events.order("start_time")
    @finished = @user.finished_events.order("start_time")
  end

  def admin_dashboard
    @user = current_user
    @user_pending_invites = @user.invites.where(status: Invite::PENDING).includes(:event, :room)
    @events = @user.upcoming_events.order("start_time")
    @finished = @user.finished_events.order("start_time")
    @company = @user.company
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_create_invite.html.erb
<%= bootstrap_form_for :invite, url: "/invite_codes" do |f| %>
  <%= f.email_field :email %>
  <%= f.submit "Send Invite"%>
<% end %>

app/views/dashboard/home.html.erb
  <h4>
  <%= attachment_image_tag(@user, :profile_image, :fill, 150, 150, format: "jpg", fallback: 'default.gif', class:"dash-picture") %>
    Welcome: <%=@user.name%>
    <br>
    <% if @user == current_user %>
      <div style="width: 150px; text-align:center;">
        <%= link_to "Edit Profile", edit_user_path(@user) %>
      </div>
      <% if @user.admin? == true %>
      <div style="width: 180px; text-align:center;">
        <%= link_to "Edit Company Profile", edit_company_path(@user) %>
      </div>
      <% end %>
    <% end %>
  </h4>

<div class="row">
<% if @user.admin? == true %>
  <div>
    <div class='col-sm-8 col-sm-offset-2'>
      <h3 class="campus-header">Send an invite to join your company:
        <%= render 'create_invite' %>
      </h3>
    </div>
  </div>
  <div class='pending-events-display col-md-5 col-md-offset-1'>
    <h3 class='pending-events-header'>My Company's Users</h3>
    <ul class='pending-events-display-list'>
      <% @user.company.users.each do |user| %>
        <div class='better-row'>
          <li class='pending-events-display-list-item'>
          <div class="better-row bottom-border">
            <div class='col-xs-4'>
              <%= link_to "#{user.name}", edit_user_path(user) %>
            </div>
          </div>
        </li>
      </div>
      <% end %>
    </ul>
  </div>
<% end %>
  <div class='pending-events-display col-md-5 col-md-offset-1'>
    <h3 class='pending-events-header'>My Created Events</h3>
    <ul class='pending-events-display-list'>
      <% if @events.empty? %>
        <li>You have not created any events</li>
      <% else %>
        <% @events.each do |event| %>
          <div class='better-row'>
            <li class='pending-events-display-list-item'>
              <div class='col-xs-4 col-xs-offset-1'>
                <%= link_to event.name.titleize, campus_room_event_path(current_user.campus, event.room.id, event.id) %>
              </div>
              <div class='time-display col-xs-7'>
                <%= event.formatted_start_time %> until <%= event.end_time %>
              </div>
            </li>
          </div>
          <div class='better-row bottom-border'>
              <div class='col-xs-4 col-xs-offset-1'>
                <%= link_to event.room.name, campus_room_path(current_user.campus, event.room.id), class:'room-name' %>
              </div>
          </div>
        <% end %>
      <% end %>
    </ul>
  </div>

  <div class='pending-events-display col-md-5 col-md-offset-1'>
    <h3 class='pending-events-header'>My Upcoming Events</h3>
    <ul class='pending-events-display-list'>
      <% if @user_pending_invites.empty? %>
        <li>You have no pending events</li>
      <% else %>
        <% @user_accepted_invites.each do |pend| %>
          <%= render partial: "shared/event_invite", locals: {invite: pend} %>
        <% end %>
      <% end %>
    </ul>
  </div>

  <div class='pending-events-display col-md-5 col-md-offset-1'>
    <h3 class='pending-events-header'>My Pending Invites</h3>
    <ul class='pending-events-display-list'>
      <% if @user_pending_invites.empty? %>
        <li>You have no pending invites</li>
      <% else %>
        <% @user_pending_invites.each do |pend| %>
          <%= render partial: "shared/event_invite", locals: {invite: pend} %>
        <% end %>
      <% end %>
    </ul>
  </div>

  <div class='pending-events-display col-md-5 col-md-offset-1'>
    <h3 class='pending-events-header'>Completed events</h3>
    <ul class='pending-events-display-list'>
      <% if @finished.empty? %>
        <li>You have no events that have been completed</li>
      <% else %>
        <% @finished.each do |event| %>
        <div class='better-row'>
          <li class='pending-events-display-list-item'>
            <div class='col-xs-4 col-xs-offset-1'>
              <%= link_to event.name.titleize, campus_room_event_path(current_user.campus, event.room.id, event.id) %>
            </div>
            <div class='time-display col-xs-7'>
              <%= event.formatted_start_time %> until <%= event.end_time %>
            </div>
          </li>
        </div>
        <div class='better-row bottom-border'>
            <div class='col-xs-4 col-xs-offset-1'>
              <%= link_to event.room.name, campus_room_path(current_user.campus, event.room.id), class:'room-name' %>
            </div>
        </div>
        <% end %>
      <% end %>
    <ul class='pending-events-display-list'>
    </ul>
  </div>
</div>