config/routes.rb
Rails.application.routes.draw do



  constraints Clearance::Constraints::SignedIn.new { |user| user.admin? } do
    resources :companies

    resources :campuses do
      resources :rooms do
        resources :events
      end
    end
  end

  get 'company' => 'companies#show'

  constraints Clearance::Constraints::SignedIn.new do

    delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
    resources :users
    resources :invites
    resources :comments
    resources :amenities

    resources :campuses do
      resources :rooms, only: [:show, :index] do
        resources :events
      end
    end

    get 'campuses/:campus_id/events' => 'campuses#events'

    post 'invite_codes' => "invite_codes#create"
    root 'dashboard#home'

    resources :passwords, controller: "clearance/passwords", only: [:create, :new]
    resource :session, controller: "clearance/sessions", only: [:create]

    resources :users, controller: "clearance/users", only: [:create] do
      resource :password,
        controller: "clearance/passwords",
        only: [:create, :edit, :update]
    end
  end

  constraints Clearance::Constraints::SignedOut.new do
    resources :passwords, controller: "clearance/passwords", only: [:create, :new]
    resource :session, controller: "clearance/sessions", only: [:create]

    resources :users, only: [:new, :create]

    resources :users, controller: "clearance/users", except: [:create] do
      resource :password,
        controller: "clearance/passwords",
        only: [:create, :edit, :update]
    end

    get "/sign_in" => "clearance/sessions#new", as: "sign_in"
    get "/sign_up" => "clearance/users#new", as: "sign_up"

    root "clearance/sessions#new", as: :guest_root
  end

end

app/views/shared/_event_invite.html.erb
<div class='row better-row sm-bottom-border'>
  <li class='pending-events-display-list-item'>

    <div class='col-xs-3 col-sm-4 col-xs-offset-1'>
      <%= link_to invite.event.name.titleize, campus_room_event_path(current_user.campus, invite.room.id, invite.event.id) %>
    </div>

    <div class='time-display col-xs-4 col-sm-7'>
      <%= invite.event.formatted_start_time %> until <%= invite.event.end_time %>
    </div>
</div>
<div class='better-row bottom-border'>
    <div class='col-xs-4 col-sm-4 col-xs-offset-1'>
      <%= link_to invite.room.name, campus_room_path(current_user.campus, invite.room.id), class:'room-name' %>
    </div>
    <% if invite.status == Invite::PENDING %>
      <div class='col-xs-7 col-sm-7'>
        <%= link_to 'Approve', invite_path(invite, invite: {status: Invite::ACCEPTED}), :class => "btn btn-default", :method => :patch %>
        <%= link_to 'Deny', invite_path(invite, invite: {status: Invite::REJECTED}), :class => "btn btn-default", :method => :patch %>
        <% if invite.event.allow_remote %>
          <%= link_to 'Remote', invite_path(invite, invite: {status: Invite::REMOTE}), :class => "btn btn-default", :method => :patch %>
        <% end %>
      </div>
    <% else %>
      <div class='col-xs-7 col-sm-7 room-name'>
        <%= invite.status %>
      </div>
    <% end %>
  </li>
</div>