config/routes.rb
Rails.application.routes.draw do



  constraints Clearance::Constraints::SignedIn.new { |user| user.admin? } do
    resources :companies

    resources :campuses do
      resources :rooms do
        resources :events
      end
    end
  end

  get 'company' => 'companies#show'

  constraints Clearance::Constraints::SignedIn.new do

    delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
    resources :users
    resources :invites
    resources :comments
    resources :amenities

    resources :campuses do
      resources :rooms, only: [:show, :index] do
        resources :events
      end
    end

    get 'campuses/:campus_id/events' => 'campuses#events'

    post 'invite_codes' => "invite_codes#create"
    root 'dashboard#home'

    resources :passwords, controller: "clearance/passwords", only: [:create, :new]
    resource :session, controller: "clearance/sessions", only: [:create]

    resources :users, controller: "clearance/users", only: [:create] do
      resource :password,
        controller: "clearance/passwords",
        only: [:create, :edit, :update]
    end
  end

  constraints Clearance::Constraints::SignedOut.new do
    resources :passwords, controller: "clearance/passwords", only: [:create, :new]
    resource :session, controller: "clearance/sessions", only: [:create]

    resources :users, only: [:new, :create]

    resources :users, controller: "clearance/users", except: [:create] do
      resource :password,
        controller: "clearance/passwords",
        only: [:create, :edit, :update]
    end

    get "/sign_in" => "clearance/sessions#new", as: "sign_in"
    get "/sign_up" => "clearance/users#new", as: "sign_up"

    root "clearance/sessions#new", as: :guest_root
  end

end

app/models/room.rb
class Room < ActiveRecord::Base
  validates :name, presence: true
  validates :location, presence: true
  validates :capacity, presence: true
  has_many :room_amenities, dependent: :destroy
  has_many :amenities, through: :room_amenities
  has_many :events, dependent: :destroy
  belongs_to :campus#, counter_cache: true

  attachment :profile_image #required for Refile (image upload)


  def self.search(search)
    if search
      find(:all, :conditions => ['name ILIKE ?', 'location ILIKE ?', 'capacity ILIKE ?', "%#{search}%"])
    else
      find(:all)
    end
  end

  def event_array(new_event = nil)
    all_events = []
    self.events.each do |event|
      if new_event && new_event.id == event.id
        event = new_event
      end
      end_time = event.start_time + (event.duration*15).minutes
      all_events << (event.start_time..end_time) unless event.created_at.nil?
    end

    if new_event && !new_event.created_at
      end_time = new_event.start_time + (new_event.duration*15).minutes
      all_events << (new_event.start_time..end_time)
    end

    all_events.sort_by{|range| range.min.to_i}
  end

  def get_event_overlap(new_event = nil)
    event_ranges = event_array(new_event)
    event_ranges.each_with_index do |event_range,index|
      if (index+1 < event_ranges.count) && (event_range.max > event_ranges[index+1].min)
        return "#{event_range} overlaps with #{event_ranges[index+1]}"
      end
    end
    return false
  end

  def event_overlap?(new_event=nil)
    !!get_event_overlap(new_event)
  end

  def average_capacity_use
    event_attendance = []
    self.events.each do |x|
      event_attendance << x.get_physical_participation
    end
    average_attendance = event_attendance.inject{ |sum, el| sum + el }.to_f / event_attendance.size
    average_attendance.round(1)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :company_validation
  before_action :get_campus, only: [:new, :create]
  before_action :get_room, only: [:show ]
  before_action :get_room_campus, only: [:update, :edit]


  def index
    @rooms = Room.where(campus_id: params[:campus_id])
    # @rooms = Room.all.order("average_capacity_use")

    respond_to do |format|
      format.json { render json: @rooms.to_json(include: :amenities) }
      format.html
    end
  end

  def show
    @room = get_room
    @events = @room.events.where(private: "false") + current_user.meetings.where(room_id: @room.id, private: "true")
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    save_for_html_json(@room, "new") {campus_room_path(@campus, @room)}
  end

  def edit
  end

  def update
    @room.assign_attributes(room_params)
    save_for_html_json(@room, "edit") {campus_room_path(@campus, @room)}
  end

  def destroy
    destroy_html_json(@room, "/")
  end



  private

  def get_room_campus
    get_room
    get_campus
  end

  def get_room
    @room = Room.find(params.fetch(:id))
  end

  def get_campus
    @campus = Campus.find(params[:campus_id])
  end

  def room_params
    params.require(:room).permit(:name, :campus_id, :location,
      :capacity, :picture_url)
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/edit.html.erb
<h1>Editing Room: <%=@room.name%></h1>
<h2> Current Campus: <%=@campus.id%> </h2>
<hr />
<div class='col-md-offset-2 col-md-6'>
  <%= form_for([@campus, @room], class: 'form') do |f| %>

    <div class='row'>
      <div class='col-md-12'>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
        <%= f.hidden_field :campus_id, :value => @campus.id %>
      </div>
    </div>
    <div class='row'>
      <div class='col-md-12'>
        <%= f.label :location%>
        <%= f.text_field :location, class: 'form-control' %>
      </div>
    </div>
    <div class='row'>
      <div class='col-md-12'>
        <%= f.label :capacity %>
        <%= f.number_field(:capacity, in: 1..30) %>
      </div>
    </div>
    <div class='row'>
      <div class='col-md-12'>
        <%= f.label :profile_image %>
        <%= f.attachment_field :profile_image %>
      </div>
    </div>
    <div class='row'>
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/rooms/index.html.erb
<h1>All Current Rooms</h1>

<%= react_component('RoomSearch', rooms: @rooms, campusID: params[:campus_id]) %>

app/views/rooms/new.html.erb
<h1>Add a New Room</h1>
<h2> Current Campus: <%=@campus.id%> </h2>
<hr />
  <%= bootstrap_form_for([@campus, @room], class: 'form') do |f| %>
    <%= f.text_field :name, class: 'form-control' %>
    <%= f.hidden_field :campus_id, :value => @campus.id %>
    <%= f.text_field :location, class: 'form-control' %>
    <%= f.number_field(:capacity, in: 1..30) %>
    <%= f.attachment_field :profile_image %>
    <%= f.submit %>
  <% end %>

app/views/rooms/show.html.erb
<div>
  <h3><strong>Viewing <%=@room.name%></strong></h3>
</div>

<div>
  <%= attachment_image_tag(@room, :profile_image, :fill, 150, 150, format: 'jpg', fallback: 'room.jpg', class:'camp-picture') %>
</div>

<div class='row pending-events-display'>
  <div class='col-sm-3 col-sm-offset-1'>
    <h4>Location <h5><%=@room.location%></h5></h4>
  </div>
  <div class='col-sm-3 col-sm-offset-1'>
    <h4>Capacity <h5><%=@room.capacity%></h5><h4>
  </div>
  <div class='col-sm-4 col-sm-offset-0'>
    <h4>List of Amenities</h4>
    <% @room.amenities.each do |amenity| %>
    <h5><%= amenity.name %></h5>
    <% end %>
  </div>
</div>

<div><%= link_to 'Create New Event', new_campus_room_event_path(@room.campus, @room), class:'btn btn-default create-event-btn' %></div>

<div class="row">
  <div class='pending-events-display col-md-12 col-md-offset-0'>
    <h4 class='pending-events-header'>Upcoming Events </h4>
    <ul class='pending-events-display-list'>
      <div class='row room-show-bottom-spacer'>
        <li class='pending-events-display-list-item'>
          <div class='col-xs-4'>
            <h5><strong>Name </strong></h5>
          </div>
          <div class='col-xs-4 agenda-text'>
            <h5><strong>Description </strong></h5>
          </div>
          <div class='time-display col-xs-4'>
            <h5><strong>Start Time </strong></h5>
          </div>
        </li>
      </div>
        <% @events.each do |event| %>
          <div class='row room-show-bottom-spacer'>
            <li class='pending-events-display-list-item'>
              <div class='col-xs-4'>
                <%= link_to "#{event.name}", campus_room_event_path(event.campus, event.room, event) %>
              </div>
              <div class='col-xs-4 agenda-text'>
                <%= event.agenda %>
              </div>
              <div class='time-display col-xs-4'>
                <%= event.formatted_start_time %> until <%= event.end_time %>
              </div>
            </li>
          </div>
        <% end %>
    </ul>
  </div>
</div>