config/routes.rb
Rails.application.routes.draw do



  constraints Clearance::Constraints::SignedIn.new { |user| user.admin? } do
    resources :companies

    resources :campuses do
      resources :rooms do
        resources :events
      end
    end
  end

  get 'company' => 'companies#show'

  constraints Clearance::Constraints::SignedIn.new do

    delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
    resources :users
    resources :invites
    resources :comments
    resources :amenities

    resources :campuses do
      resources :rooms, only: [:show, :index] do
        resources :events
      end
    end

    get 'campuses/:campus_id/events' => 'campuses#events'

    post 'invite_codes' => "invite_codes#create"
    root 'dashboard#home'

    resources :passwords, controller: "clearance/passwords", only: [:create, :new]
    resource :session, controller: "clearance/sessions", only: [:create]

    resources :users, controller: "clearance/users", only: [:create] do
      resource :password,
        controller: "clearance/passwords",
        only: [:create, :edit, :update]
    end
  end

  constraints Clearance::Constraints::SignedOut.new do
    resources :passwords, controller: "clearance/passwords", only: [:create, :new]
    resource :session, controller: "clearance/sessions", only: [:create]

    resources :users, only: [:new, :create]

    resources :users, controller: "clearance/users", except: [:create] do
      resource :password,
        controller: "clearance/passwords",
        only: [:create, :edit, :update]
    end

    get "/sign_in" => "clearance/sessions#new", as: "sign_in"
    get "/sign_up" => "clearance/users#new", as: "sign_up"

    root "clearance/sessions#new", as: :guest_root
  end

end

app/controllers/campuses_controller.rb
class CampusesController < ApplicationController
before_action :company_validation, except: [:index]
before_action :set_campus, only: [:show, :update, :destroy]
  def index
    @campuses = current_user.company.campuses
  end

  def show
    @rooms = @campus.rooms.includes(:events).sort_by{ |room| -room.average_capacity_use }
  end

  def new
    @campus = Campus.new
  end

  def create
    @campus = Campus.new(campus_params)
    @campus.company_id = current_user.company.id
    save_for_html_json(@campus, "show") { campus_path(@campus) }
  end

  def update
    @campus.assign_attributes(campus_params)
    save_for_html_json(@campus, "edit") { campus_path(@campus) }
  end

  def destroy
    destroy_html_json(@campus, campus_path(@campus))
  end

  def events
    @campus = Campus.find(params[:campus_id])
    if current_user.admin?
      @campus_events = @campus.all_events
    else
      @campus_events = @campus.public_events
    end

    @campus_events = @campus.events.includes(:room, :user)
    respond_to do |format|
      format.html { }
      format.pdf do
        render pdf: 'event-report', disable_external_links: true, template: 'campuses/events.html.erb'
      end
      format.csv do
        render text: @campus_events.to_csv
      end
    end
  end

  private

    def set_campus
      @campus = Campus.find(params[:id])
    end

    def campus_params
      params.require(:campus)
    end

end

app/helpers/campuses_helper.rb
module CampusesHelper
end

app/views/campuses/_form.html.erb
<%= bootstrap_form_for @campus do |f| %>
  <% if @campus.errors.any? %>
      <h2><%= pluralize(@campus.errors.count, "error") %> prohibited this campus from being saved:</h2>
      <ul>
      <% @campus.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <%= f.text_field :name %>
    <%= f.text_field :city %>
    <%= f.text_field :state %>
    <%= f.text_field :zip %>
    <%= f.attachment_field :profile_image %>
    <%= f.submit %>
<% end %>

app/views/campuses/edit.html.erb
<p id="notice"><%= notice %></p>
<h1>Editing campus</h1>

<%= render 'form' %>

<%= link_to 'Show', @campus %> |
<%= link_to 'Back', campus_path %>

app/views/campuses/events.html.erb
<h1>Listing Events for <%= "#{@campus.name}" %></h1>
<% if current_user.admin == true %>
    <a class='btn btn-default not-pdf-friendly pull-left' href='/campuses/<%= "#{@campus.id}" %>/events.pdf'>PDF Report of page</a>
    <a class='btn btn-default not-pdf-friendly pull-left' href='/campuses/<%= "#{@campus.id}" %>/events.csv'>Spreadsheet report of page</a>
<% end %>

<div class="better-row">
  <div class='pending-events-display campus-event-box col-md-12 col-md-offset-0'>
    <h4 class='pending-events-header'></h4>
    <ul class='pending-events-display-list'>
      <div class='better-row room-show-bottom-spacer'>
        <li class='pending-events-display-list-item'>
          <div class='col-xs-2'>
            <h5><strong>Name </strong></h5>
          </div>
          <div class='agenda-text col-xs-2 '>
            <h5><strong>Start Time </strong></h5>
          </div>
          <div class='time-display col-xs-2'>
            <h5><strong>Description </strong></h5>
          </div>
          <div class='col-xs-2'>
            <h5><strong>Room </strong></h5>
          </div>
          <div class=' col-xs-2'>
            <h5><strong>User </strong></h5>
          </div>
          <div class='col-xs-2'>
            <% if current_user.admin == true %>
            <h5>Edit </h5>
            <h5>Delete </h5>
            <% end %>
          </div>
        </li>
      </div>
      <% @campus_events.each do |event| %>
          <div class='better-row room-show-bottom-spacer'>
            <li class='pending-events-display-list-item'>
              <div class='col-xs-2'>
                <%= link_to "#{event.name}", campus_room_event_path(event.campus, event.room, event) %>
              </div>
              <div class='time-display col-xs-2'>
                <%= event.formatted_start_time %> until <%= event.end_time %>
              </div>
              <div class='col-xs-2'>
                <%= event.description %>
              </div>
              <div class='col-xs-2'>
                <%= event.room.name %>
              </div>
              <div class='col-xs-2'>
                <%= event.user.username %>
              </div>
              <div class='col-xs-2'>
                <% if current_user.admin == true %>
                <%= link_to 'Edit Event Details', edit_campus_room_event_path(event.campus, event.room, event), class: "btn btn-default btn-custom not-pdf-friendly" %>
                <%= link_to 'Delete Event', campus_room_event_path(event.campus, event.room, event), class: "btn btn-default btn-custom not-pdf-friendly", method: :delete, data: { confirm: 'Are you sure?' } %>
                <% end %>
              </div>
            </li>
          </div>
        <% end %>
    </ul>
  </div>
</div>

app/views/campuses/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">

  <h1>Listing campuses</h1>

      <% @campuses.each do |campus| %>
          <%= campus.name %> <br>
          <%= attachment_image_tag(campus, :profile_image, :fill, 150, 150, format: "jpg", fallback: 'campus.jpg', class:"camp-picture") %>
          <%= link_to 'Show', campus %><br>
          <hr>
      <% end %>

app/views/campuses/new.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <h1>New Campus</h1>

  <%= render 'form' %>

  <%= link_to 'Back', campuses_path %>
</div>

app/views/campuses/show.html.erb
<div class='row pending-events-display'>
  <div class='col-sm-8 col-sm-offset-1'>
    <h3 class="campus-header">
      <strong>Campus:</strong>
      <%= @campus.name %>
    </h3>
  </div>
  <div class='col-sm-2 col-sm-offset-1'>
    <%= attachment_image_tag(@campus, :profile_image, :fill, 150, 150, format: "jpg", fallback: 'campus.jpg', class:"camp-picture") %>
  </div>
</div>
  <div class="pull-right">
      <%= link_to 'Create New Room', new_campus_room_path(@campus) %>
  </div>
<% @rooms.each_slice(2) do |rooms| %>
  <div class="row">
    <div class='col-sm-12'>
      <% rooms.each_with_index do |room, index| %>
        <div class="pending-events-display campus-room col-sm-5 col-sm-offset-<%= 2 if index == 1 %>">
          <h3 id="room-name"><%= link_to room.name, campus_room_path(@campus, room) %></h3>
          <%= attachment_image_tag(room, :profile_image, :fill, 150, 150, format: "jpg", fallback: 'room.jpg', class:"camp-picture") %>
          <div class="row campus-description-padding">
            <div class="col-sm-6">
              <%= room.location %>
            </div>
            <div class="col-sm-6">
              <p>capacity <%= room.capacity %></p>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-6">
              <p><%= room.events_count %> Events</p>
            </div>
            <div class="col-sm-6">
              <p>Avg Use <%= room.average_capacity_use %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>
<div class='row'>
  <%= link_to 'Back', campuses_path %>
</div>